stateDiagram-v2
    _:  
    Fitness: Fitness
    __1:  
    Welcome_to_Fitness: Welcome to Fitness
    [*] --> _
    _ --> Fitness: Fitness
    Fitness --> __1: See Your Activity, Keep up with your rings, workouts, awards, and trends.
    __1 --> Welcome_to_Fitness: Не разрешать
    Welcome_to_Fitness --> Welcome_to_Fitness: See Your Activity, Keep up with your rings, workouts, awards, and trends.
    Welcome_to_Fitness --> Welcome_to_Fitness: Track Your Workouts, See metrics like your pace and distance, or connect a device with a heart rate sensor for more workout types and data.