stateDiagram-v2
    TestApp: TestApp
    Вход: Вход
    Вход_1: Вход
    Профиль: Профиль
    Настройки: Настройки
    TestApp_1: TestApp
    TestApp_2: TestApp
    Вход_2: Вход
    Вход_3: Вход
    [*] --> TestApp
    TestApp --> Вход: Выйти
    Вход --> Вход_1: Войти
    Вход_1 --> Вход_1: Войти
    Вход_1 --> Профиль: input (valid)
    Профиль --> Настройки: Настройки
    Настройки --> TestApp: Выйти из аккаунта
    TestApp --> Настройки: Отмена
    Настройки --> Настройки: Русский
    Настройки --> Настройки: English
    Настройки --> TestApp_1: Очистить кэш
    TestApp_1 --> Настройки: OK
    Настройки --> Профиль: Профиль
    Профиль --> TestApp_2: Удалить аккаунт
    TestApp_2 --> Вход_2: Удалить
    Вход_2 --> Вход_3: Войти