stateDiagram-v2
    Вход: Вход
    TestApp: TestApp
    Профиль: Профиль
    Профиль_1: Профиль
    Настройки: Настройки
    TestApp_1: TestApp
    [*] --> Вход
    Вход --> TestApp: Войти
    TestApp --> Вход: OK
    Вход --> Профиль: input (valid)
    Профиль --> Вход: Вход
    Профиль --> Профиль_1: Редактировать
    Профиль_1 --> Вход: Вход
    Профиль --> Настройки: Настройки
    Настройки --> TestApp_1: Выйти из аккаунта