stateDiagram-v2
    Вход: Вход
    Профиль: Профиль
    Вход_1: Вход
    Профиль_1: Профиль
    Настройки: Настройки
    TestApp: TestApp
    TestApp_1: TestApp
    TestApp_2: TestApp
    TestApp_3: TestApp
    4f53cda1: 4f53cda1
    [*] --> Вход
    Вход --> Профиль: input (valid)
    Профиль --> Вход_1: Вход
    Вход_1 --> Профиль: input (valid)
    Профиль --> Профиль_1: Редактировать
    Профиль_1 --> Вход_1: Вход
    Профиль --> Настройки: Настройки
    Настройки --> Профиль: Профиль
    Профиль --> TestApp: Удалить аккаунт
    TestApp --> Профиль: Отмена
    Профиль_1 --> Вход: input (valid)
    Настройки --> Настройки: Русский
    Настройки --> Настройки: English
    Настройки --> TestApp_1: Очистить кэш
    TestApp_1 --> Настройки: OK
    Настройки --> TestApp_2: Выйти из аккаунта
    TestApp_2 --> Настройки: Отмена
    Профиль_1 --> TestApp_3: Сохранить
    TestApp_3 --> Профиль: OK
    Профиль_1 --> Профиль: Отмена
    Вход_1 --> Профиль: Войти
    Профиль_1 --> Настройки: Настройки