stateDiagram-v2
    Вход: Вход
    Профиль: Профиль
    Настройки: Настройки
    TestApp: TestApp
    Вход_1: Вход
    Профиль_1: Профиль
    Вход_2: Вход
    Вход_3: Вход
    TestApp_1: TestApp
    TestApp_2: TestApp
    Вход_4: Вход
    Вход_5: Вход
    TestApp_3: TestApp
    [*] --> Вход
    Вход --> Вход: Войти
    Вход --> Профиль: input (valid)
    Профиль --> Настройки: Настройки
    Настройки --> Профиль: Профиль
    Профиль --> TestApp: Удалить аккаунт
    TestApp --> Вход_1: Удалить
    Вход_1 --> Вход: Войти
    Профиль --> Профиль_1: Редактировать
    Профиль_1 --> Вход_2: Вход
    Вход_2 --> Профиль: Войти
    Профиль --> Вход_2: Вход
    Вход_2 --> Профиль: input (valid)
    Профиль_1 --> Вход_3: input (valid)
    Вход_3 --> Вход_3: Войти
    Вход_3 --> Профиль: input (valid)
    Настройки --> Настройки: Русский
    Настройки --> Настройки: English
    Настройки --> TestApp_1: Очистить кэш
    TestApp_1 --> Настройки: OK
    Настройки --> TestApp_2: Выйти из аккаунта
    TestApp_2 --> Вход_4: Выйти
    Вход_4 --> Вход_5: Войти
    Вход_5 --> Вход_5: Войти
    Вход_5 --> Профиль: input (valid)
    Вход_1 --> Профиль: input (valid)
    Вход_4 --> Профиль: input (valid)
    Профиль_1 --> TestApp_3: Сохранить
    TestApp_3 --> Профиль: OK
    Профиль_1 --> Профиль: Отмена
    Вход_5 --> Настройки: Настройки
    Профиль_1 --> Настройки: Настройки
    Вход --> Профиль: Профиль
    Вход_4 --> Настройки: Настройки
    Профиль_1 --> TestApp: Удалить аккаунт
    TestApp --> Профиль_1: Отмена
    TestApp_2 --> Настройки: Отмена
    Вход_1 --> Профиль: Профиль